channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy<2.0
  - gdal>=3.7, <3.9
  - conda-forge::osmnx<2.0, >=1.3
  - dataclasses
  - seaborn
  - cmocean
  - scipy>=1.6.0
  - shapely>=2.0
  - pandas
  - requests
  - geopandas
  - bottleneck
  - numexpr
